### ISSUE TITLE
Highlighting of variables with dash in name

### ISSUE THREAD

**Issue by simark** [bdavs/expect#1]
In tcl, it's possible to have variable names with dashes in them, like so:

![image](https://user-images.githubusercontent.com/1758287/104967187-c3430e80-59b0-11eb-884b-92d22ed755f6.png)

As you can see, the highlighting doesn't work well with that.

**Comment by bdavs** [comment]
#2

**Comment by bdavs** [comment]
The recent merge should take care of this issue

**Comment by simark** [comment]
Thanks!
